"""empty message

Revision ID: 1ebd0adbf272
Revises: 94dc1abddc41
Create Date: 2019-09-13 20:51:41.934499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebd0adbf272'
down_revision = '94dc1abddc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website', sa.Column('site_props', sa.String(), nullable=True))
    op.drop_column('website', 'layout')
    op.drop_column('website', 'navigation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website', sa.Column('navigation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('website', sa.Column('layout', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('website', 'site_props')
    # ### end Alembic commands ###
