"""empty message

Revision ID: 50b28b233289
Revises: 258ef5d804d8
Create Date: 2019-11-14 17:22:46.171753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b28b233289'
down_revision = '258ef5d804d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_stats',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('visit_date_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_stats')
    # ### end Alembic commands ###
