"""empty message

Revision ID: 6c46cd4eac6c
Revises: 1ebd0adbf272
Create Date: 2019-09-13 20:52:36.314930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c46cd4eac6c'
down_revision = '1ebd0adbf272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website', 'site_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website', sa.Column('site_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
