"""empty message

Revision ID: 723b1f06124f
Revises: 6d2af7040f85
Create Date: 2019-08-02 14:48:16.547907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723b1f06124f'
down_revision = '6d2af7040f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('f_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('s_name', sa.String(), nullable=False))
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_column('user', 's_name')
    op.drop_column('user', 'f_name')
    # ### end Alembic commands ###
