"""empty message

Revision ID: 7911a719bc34
Revises: 8709ed798778
Create Date: 2019-12-07 19:37:06.692774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7911a719bc34'
down_revision = '8709ed798778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'website_stats', 'user', ['domain'], ['domain'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'website_stats', type_='foreignkey')
    # ### end Alembic commands ###
