"""empty message

Revision ID: 8709ed798778
Revises: 72e69b55aafd
Create Date: 2019-12-07 14:47:42.559777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8709ed798778'
down_revision = '72e69b55aafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('website_domain_fkey', 'website', type_='foreignkey')
    op.drop_constraint('website_user_id_fkey', 'website', type_='foreignkey')
    op.create_foreign_key(None, 'website', 'user', ['user_id'], ['u_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'website', 'user', ['domain'], ['domain'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'website', type_='foreignkey')
    op.drop_constraint(None, 'website', type_='foreignkey')
    op.create_foreign_key('website_user_id_fkey', 'website', 'user', ['user_id'], ['u_id'])
    op.create_foreign_key('website_domain_fkey', 'website', 'user', ['domain'], ['domain'])
    # ### end Alembic commands ###
