"""empty message

Revision ID: ce0af8ba8a4d
Revises: b03456c53569
Create Date: 2019-08-04 19:01:35.161543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0af8ba8a4d'
down_revision = 'b03456c53569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website', sa.Column('layout', sa.String(), nullable=True))
    op.add_column('website', sa.Column('navigation', sa.Integer(), nullable=True))
    op.add_column('website', sa.Column('site_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website', 'site_name')
    op.drop_column('website', 'navigation')
    op.drop_column('website', 'layout')
    # ### end Alembic commands ###
